version: '3.8'

services:
    postgres:
      image: postgres:12
      restart: always
      container_name: postgres-12
      environment:
        - "POSTGRES_DB=docker_pg_db"
        - "POSTGRES_USER=postgres"
        - "POSTGRES_PASSWORD=paSSw0rd"
      volumes:
        - ./db-data/postgres-12:/var/lib/postgresql
      ports:
        - 15432:5432

    mssql:
      image: mcr.microsoft.com/mssql/server:2017-latest
      restart: always
      container_name: mssql-2017
      environment:
        - "ACCEPT_EULA=Y"
        - "SA_PASSWORD=paSSw0rd123"
      ports:
        - 11433:1433
      volumes:
        - ./db-data/mssql-2017:/var/opt/mssql

    mysql:
      image: mysql:5
      restart: always
      container_name: mysql-5
      ports:
        - 13306:3306
      environment:
        - "MYSQL_ROOT_PASSWORD=paSSw0rd"
        - "MYSQL_DATABASE=docker_mysql_db"
        - "MYSQL_USER=mysql"
        - "MYSQL_PASSWORD=paSSw0rd"
      volumes:
        - ./db-data/mysql-5:/var/lib/mysql

    hsqldb:
      image: blacklabelops/hsqldb
      restart: always
      container_name: hsqldb
      ports:
        - 19001:9001
      environment:
        - "HSQLDB_DATABASE_NAME=docker_hsqldb"
        - "HSQLDB_DATABASE_ALIAS=docker_hsqldb"
        - "HSQLDB_USER=hsqldb"
        - "HSQLDB_PASSWORD=paSSw0rd"
      volumes:
        - ./db-data/hsqldb5:/opt/database

    adminer:
      image: adminer:4
      container_name: adminer
      restart: always
      ports:
        - 8081:8080
